export const testallPlayers = [
    {name:'J Sharma', group:'Keeper'},
    {name:'Saha', group:'Keeper'},
    {name:'Gill', group:'Batsman'},
    {name:'Miller', group:'Batsman'},
    {name:'Rajapaksa', group:'Batsman'},
    {name:'S Sudarshan', group:'Batsman'},
    {name:'Shahrukh', group:'Batsman'},
    {name:'Curran', group:'All-Rounder'},
    {name:'Pandya', group:'All-Rounder'},
    {name:'R Dhawan', group:'All-Rounder'},
    {name:'Short', group:'All-Rounder'},
    {name:'Raza', group:'All-Rounder'},
    {name:'Shankar', group:'All-Rounder'},
    {name:'Rabada', group:'Bowler'},
    {name:'Rashid', group:'Bowler'},
    {name:'Arshdeep', group:'Bowler'},
    {name:'Shami', group:'Bowler'},
    {name:'Mohit', group:'Bowler'},
    {name:'Alzari Joseph', group:'Bowler'},
    {name:'Chahar', group:'Bowler'},
    {name:'Mavi', group:'Bowler'},];

export const testtopPlayers = [
    {name:'Saha', group:'Keeper'},
    {name:'Gill', group:'Batsman'},
    {name:'S Sudarshan', group:'Batsman'},
    {name:'Short', group:'All-Rounder'},
    {name:'Shankar', group:'All-Rounder'},
    {name:'Rabada', group:'Bowler'},
    {name:'Rashid', group:'Bowler'},
    {name:'Arshdeep', group:'Bowler'},
    {name:'Shami', group:'Bowler'},
    {name:'Mohit', group:'Bowler'}];